### ISSUE TITLE
cani join?

### ISSUE THREAD

**Issue by matthew4444** [Code-Adic-Team/Code-Adic-Team-Members#1]
can i join? i have a suprise for u

**Comment by HittmanA** [comment]
Sure. What is the surprise?

**Comment by matthew4444** [comment]
GLADIATORMINE ORG

**Comment by HittmanA** [comment]
Cool!!!!!!

**Comment by HittmanA** [comment]
BTW matthew can you set your organization visibility to public?

**Comment by matthew4444** [comment]
kk

**Comment by HittmanA** [comment]
thanks!

**Comment by farazfazli** [comment]
May I join too @HittmanA? Thanks! :)

**Comment by HittmanA** [comment]
Hello @farazfazli. I have taken a look at your profile and some of your work and you look like you are more than qualified to join. Welcome to the team!

**Comment by farazfazli** [comment]
Thanks @HittmanA!

**Comment by HittmanA** [comment]
No problem!

**Comment by farazfazli** [comment]
@HittmanA I have no experience with PHP, can we build this out in Go?

**Comment by HittmanA** [comment]
Yeah sure. Thanks again!

**Comment by HittmanA** [comment]
@farazfazli I am going to open a gitter room for us to talk about the website if that's ok.

**Comment by farazfazli** [comment]
@HittmanA Sure, that sounds excellent.

**Comment by HittmanA** [comment]
Ok I will send you an invite.
